FROM python:3.9.16

RUN pip install pandas sqlalchemy psycopg2
RUN apt-get install wget

WORKDIR /app 

COPY ingest_data_zones.py ingest_data_zones.py

ENTRYPOINT [ "python", "ingest_data_zones.py" ]
