Hey, I'm Jobert Gutierrez and hereafter you'll find the logic and code used to answer the fourth assignment in the program Data Engineering Zoomcamp offered by Data Talks Club.

# __Module 4 Homework__

### Data talks club data engineering zoomcamp Data loading workshop

The `linked colab notebook` offers a few exercises to practice what you learned today.

__Important Note:__

I replicated the code here below, so you can copy & paste it to check the answer in the original `colab notebook` avalible at: https://colab.research.google.com/drive/1Te-AT0lfh0GpChg1Rbd0ByEKOHYtWXfm#scrollTo=wLng-bDJN4jf&forceEdit=true&sandboxMode=true


### Preparation.

### Part 1. __Use a generator__

Remember the concept of generator? Let's practice using them to futher our understanding of how they work.

Let's define a generator and then run it as practice.

In [1]:
def square_root_generator(limit):
    n = 1
    while n <= limit:
        yield n ** 0.5
        n += 1

# Example usage:
limit = 5
generator = square_root_generator(limit)

for sqrt_value in generator:
    print(sqrt_value)

1.0
1.4142135623730951
1.7320508075688772
2.0
2.23606797749979


## Answer the following questions:
### Question 1: 
What is the sum of the outputs of the generator for limit = 5?

- A: 10.23433234744176
- B: 7.892332347441762
- C: 8.382332347441762
- D: 9.123332347441762



### Answer: 
To get the answer required, I slightly modified the `generator`'s code by using an auxiliary variable to sum the current iteration result's to it's previous values. 

In [2]:
def square_root_generator(limit):
    n = 1
    while n <= limit:
        yield n ** 0.5
        n += 1

# Example usage:
limit = 5
generator = square_root_generator(limit)

sum_values = 0 # Using an auxiliary variable to get the sums up to every iteration
for sqrt_value in generator:
    sum_values = sum_values + sqrt_value 
    print(sqrt_value," | ",sum_values) # And modifying the print statement to get the result

1.0  |  1.0
1.4142135623730951  |  2.414213562373095
1.7320508075688772  |  4.146264369941973
2.0  |  6.146264369941973
2.23606797749979  |  8.382332347441762


From the above excerpt it's clearly appreciated that the correct answer is __C: 8.382332347441762__.

## Question 2:
What is the 13th number yielded by the generator?

- A: 4.236551275463989
- B: 3.605551275463989
- C: 2.345551275463989
- D: 5.678551275463989

## Answer:

Using the same modified code as in question one, I get:

In [3]:
def square_root_generator(limit):
    n = 1
    while n <= limit:
        yield n ** 0.5
        n += 1

# Example usage:
limit = 13  # This time I set the limit to 13 
generator = square_root_generator(limit)

sum_values = 0
for sqrt_value in generator:
    sum_values = sum_values +sqrt_value 
    print(sqrt_value," | ",sum_values)

1.0  |  1.0
1.4142135623730951  |  2.414213562373095
1.7320508075688772  |  4.146264369941973
2.0  |  6.146264369941973
2.23606797749979  |  8.382332347441762
2.449489742783178  |  10.83182209022494
2.6457513110645907  |  13.47757340128953
2.8284271247461903  |  16.30600052603572
3.0  |  19.30600052603572
3.1622776601683795  |  22.4682781862041
3.3166247903554  |  25.7849029765595
3.4641016151377544  |  29.249004591697254
3.605551275463989  |  32.854555867161245


From the results above, I can identiy that the correct answer is __B: 3.605551275463989__.

### Part 2. __Append a generator to a table with existing data__

Below you have 2 generators. You will be tasked to load them to duckdb and answer some questions from the data

1. Load the first generator and calculate the sum of ages of all people. Make sure to only load it once.
2. Append the second generator to the same table as the first.

In [4]:
def people_1():
    for i in range(1, 6):
        yield {"ID": i, "Name": f"Person_{i}", "Age": 25 + i, "City": "City_A"}

for person in people_1():
    print(person)


def people_2():
    for i in range(3, 9):
        yield {"ID": i, "Name": f"Person_{i}", "Age": 30 + i, "City": "City_B", "Occupation": f"Job_{i}"}


for person in people_2():
    print(person)

{'ID': 1, 'Name': 'Person_1', 'Age': 26, 'City': 'City_A'}
{'ID': 2, 'Name': 'Person_2', 'Age': 27, 'City': 'City_A'}
{'ID': 3, 'Name': 'Person_3', 'Age': 28, 'City': 'City_A'}
{'ID': 4, 'Name': 'Person_4', 'Age': 29, 'City': 'City_A'}
{'ID': 5, 'Name': 'Person_5', 'Age': 30, 'City': 'City_A'}
{'ID': 3, 'Name': 'Person_3', 'Age': 33, 'City': 'City_B', 'Occupation': 'Job_3'}
{'ID': 4, 'Name': 'Person_4', 'Age': 34, 'City': 'City_B', 'Occupation': 'Job_4'}
{'ID': 5, 'Name': 'Person_5', 'Age': 35, 'City': 'City_B', 'Occupation': 'Job_5'}
{'ID': 6, 'Name': 'Person_6', 'Age': 36, 'City': 'City_B', 'Occupation': 'Job_6'}
{'ID': 7, 'Name': 'Person_7', 'Age': 37, 'City': 'City_B', 'Occupation': 'Job_7'}
{'ID': 8, 'Name': 'Person_8', 'Age': 38, 'City': 'City_B', 'Occupation': 'Job_8'}


## Question 3. 
Append the 2 generators. After correctly appending the data, calculate the sum of all ages of people.

- A: 353
- B: 365
- C: 378
- D: 390

## Answer:

Using the code:

In [5]:
# to do: homework :)

import dlt

# define the connection to load into duckdb as requested
generators_pipeline = dlt.pipeline(destination='duckdb', dataset_name='generators')

# I start by loading the first generator:
def people_1():
    for i in range(1, 6):
        yield {"ID": i, "Name": f"Person_{i}", "Age": 25 + i, "City": "City_A"}

info = generators_pipeline.run(people_1(),
										table_name="gen1",
										write_disposition="replace")

# I decided to inspect the outcome metadata returned by the load by printing it.
print(info)

Pipeline dlt_ipykernel_launcher load step completed in 0.66 seconds
1 load package(s) were loaded to destination duckdb and into dataset generators
The duckdb destination used duckdb:///c:\Users\jober\data_engineering_zoomcamp\de_zoomcamp_homeworks\homework4\dlt_ipykernel_launcher.duckdb location to store data
Load package 1707793561.5318427 is LOADED and contains no failed jobs


In [6]:
# Then I check the sum of ages od all people in generator 1 by using the following code:
import duckdb

# Firstly, I create a connection to the database in duckdb
conn = duckdb.connect(f"{generators_pipeline.pipeline_name}.duckdb")

# to see the tables
conn.sql(f"SET search_path = '{generators_pipeline.dataset_name}'")
print('Loaded tables: ')
display(conn.sql("show tables")) # Here I validate that the table gen1 was properly created

# and to see the data in gen1
print("gen1 table below:")
people_gen1 = conn.sql("SELECT * FROM gen1").df()
display(people_gen1)

# Then using a sql request from gen1 we get the sum of ages as follows:
print("The sum of ages from all people in gen1 is:")
ages_gen1 = conn.sql("SELECT sum(age) as sum_age FROM gen1").df()
display(ages_gen1)

Loaded tables: 


┌─────────────────────┐
│        name         │
│       varchar       │
├─────────────────────┤
│ _dlt_loads          │
│ _dlt_pipeline_state │
│ _dlt_version        │
│ gen1                │
│ gen1_p4             │
└─────────────────────┘

gen1 table below:


id      name  age    city        _dlt_load_id         _dlt_id occupation
0   1  Person_1   26  City_A  1707793561.5318427  ngoRBcmPxz5+6w       None
1   2  Person_2   27  City_A  1707793561.5318427  h/H8m4BZ12zWMQ       None
2   3  Person_3   28  City_A  1707793561.5318427  sjzHWfEpcGw+Vg       None
3   4  Person_4   29  City_A  1707793561.5318427  7oeIsaGxyZ+I1g       None
4   5  Person_5   30  City_A  1707793561.5318427  LxTYVm2xrsOXuQ       None

The sum of ages from all people in gen1 is:


sum_age
0    140.0

In [7]:
# To append the results of the second generator to the first one, I use the code:
def people_2():
    for i in range(3, 9):
        yield {"ID": i, "Name": f"Person_{i}", "Age": 30 + i, "City": "City_B", "Occupation": f"Job_{i}"}

# Appending the registries to the same table means adding them to gen1. 
info = generators_pipeline.run(people_2(),
										table_name="gen1",
										write_disposition="append")

In [8]:
# and to check the data in gen1 out 
print("\n the new data in gen1 table is shown below:")
people_gen1 = conn.sql("SELECT * FROM gen1").df()
display(people_gen1)

# Then using a sql request from gen1 we get the sum of ages as follows:
print("\n The sum of ages from all people in gen1 (from generator1 and generator2) is:")
ages_gen1 = conn.sql("SELECT sum(age) as sum_age FROM gen1").df()
display(ages_gen1)


 the new data in gen1 table is shown below:


id      name  age    city        _dlt_load_id         _dlt_id occupation
0    1  Person_1   26  City_A  1707793561.5318427  ngoRBcmPxz5+6w       None
1    2  Person_2   27  City_A  1707793561.5318427  h/H8m4BZ12zWMQ       None
2    3  Person_3   28  City_A  1707793561.5318427  sjzHWfEpcGw+Vg       None
3    4  Person_4   29  City_A  1707793561.5318427  7oeIsaGxyZ+I1g       None
4    5  Person_5   30  City_A  1707793561.5318427  LxTYVm2xrsOXuQ       None
5    3  Person_3   33  City_B  1707793563.2571623  JuwtAXkh4jZ9zA      Job_3
6    4  Person_4   34  City_B  1707793563.2571623  LeIfB6DbmZPcjQ      Job_4
7    5  Person_5   35  City_B  1707793563.2571623  vubuiLzIWZ4wHg      Job_5
8    6  Person_6   36  City_B  1707793563.2571623  fw/C219yIytxEw      Job_6
9    7  Person_7   37  City_B  1707793563.2571623  0II9UP/yLsq91A      Job_7
10   8  Person_8   38  City_B  1707793563.2571623  nVI7FxcRL6i6oA      Job_8


 The sum of ages from all people in gen1 (from generator1 and generator2) is:


sum_age
0    353.0

Using the code snippets above, we calculate the sum of all ages of people as __'A: 353'.__

### Part 3. __Merge a generator__
Re-use the generators from Exercise 2.

A table's primary key needs to be created from the start, so load your data to a new table with primary key ID.

Load your first generator first, and then load the second one with merge. Since they have overlapping IDs, some of the records from the first load should be replaced by the ones from the second load.

After loading, you should have a total of 8 records, and ID 3 should have age 33.

## Question 4. 
Merge the 2 generators using the ID column. Calculate the sum of ages of all the people loaded as described above.
- A: 215
- B: 266
- C: 241
- D: 258

## Answer:

Using following the code:

In [9]:
# In this case I use the same pipeline of created for exercise 3 so it doesn't need to be created.

# I start by loading the first generator in a new table "gen1_p4":
info = generators_pipeline.run(people_1(),
										table_name="gen1_p4",
                                        primary_key="id",
										write_disposition="replace")

# I decided to inspect the outcome metadata returned by the load by printing it.
print(info)

# Then I load the second generator in the same table with the write disposition "merge"
# This ensure registries with same ID get updated
info = generators_pipeline.run(people_2(),
										table_name="gen1_p4",
                                        primary_key="id",
										write_disposition="merge")

# To see if the second load was performed ok I print the outcome metadata.
print(info)

Pipeline dlt_ipykernel_launcher load step completed in 0.72 seconds
1 load package(s) were loaded to destination duckdb and into dataset generators
The duckdb destination used duckdb:///c:\Users\jober\data_engineering_zoomcamp\de_zoomcamp_homeworks\homework4\dlt_ipykernel_launcher.duckdb location to store data
Load package 1707793564.6901357 is LOADED and contains no failed jobs
Pipeline dlt_ipykernel_launcher load step completed in 0.82 seconds
1 load package(s) were loaded to destination duckdb and into dataset generators
The duckdb destination used duckdb:///c:\Users\jober\data_engineering_zoomcamp\de_zoomcamp_homeworks\homework4\dlt_ipykernel_launcher.duckdb location to store data
Load package 1707793566.2108777 is LOADED and contains no failed jobs


In [10]:
# Finallly, to check the data merged
print("\n the merged data in gen1_p4 table is shown below:")
people_gen1 = conn.sql("SELECT * FROM gen1_p4").df()
display(people_gen1)

# Then using a sql request from gen1 we get the sum of ages as follows:
print("\n The sum of ages from all people in gen1_p4 (from generator1 and generator2 merged) is:")
ages_gen1 = conn.sql("SELECT sum(age) as sum_age FROM gen1_p4").df()
display(ages_gen1)


 the merged data in gen1_p4 table is shown below:


id      name  age    city        _dlt_load_id         _dlt_id occupation
0   1  Person_1   26  City_A  1707793564.6901357  yUOb3CZBbymo6w       None
1   2  Person_2   27  City_A  1707793564.6901357  lk1XmQyfWL3kMw       None
2   7  Person_7   37  City_B  1707793566.2108777  vv1pl13Q4gTEOw      Job_7
3   3  Person_3   33  City_B  1707793566.2108777  G7KrG1F4BC4onw      Job_3
4   6  Person_6   36  City_B  1707793566.2108777  mX6IAbhFpxRb4g      Job_6
5   5  Person_5   35  City_B  1707793566.2108777  8UXJN8S3SShraQ      Job_5
6   8  Person_8   38  City_B  1707793566.2108777  KRYMfgoZS7Nkpw      Job_8
7   4  Person_4   34  City_B  1707793566.2108777  XtgXV08m8Ve1LA      Job_4


 The sum of ages from all people in gen1_p4 (from generator1 and generator2 merged) is:


sum_age
0    266.0

Using the code snippets above, we calculate the sum of all ages of people as __'B: 266'.__ from the registries merged.